#if !canImport(ObjectiveC)
import XCTest

extension CodableDictionaryKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodableDictionaryKeyTests = [
        ("test_enumKey", test_enumKey),
        ("test_integerKey", test_integerKey),
        ("test_originalRawRepresentableKey", test_originalRawRepresentableKey),
    ]
}

extension CodableDictionaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodableDictionaryTests = [
        ("test_intEnumKey", test_intEnumKey),
        ("test_intKey", test_intKey),
        ("test_stringEnumKey", test_stringEnumKey),
        ("test_stringKey", test_stringKey),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodableDictionaryKeyTests.__allTests__CodableDictionaryKeyTests),
        testCase(CodableDictionaryTests.__allTests__CodableDictionaryTests),
    ]
}
#endif
